### ISSUE TITLE
Alignment issue in Navigation bar icons 

### ISSUE THREAD

**Issue by stuartbreckenridge** [vincode-io/Zavala#102]
When navigating from Collection to All, the alignment of the trailing navigation bar icons changes. 

![BA07DE70-E961-4A9E-BA9A-D3BEB1E584E2](https://user-images.githubusercontent.com/7046652/124042211-eaf7d180-da3a-11eb-9e7a-211295e86903.jpeg)

**Comment by vincode-io** [comment]
This doesn't happen on my iPhone 12 mini. What device are you using?

**Comment by stuartbreckenridge** [comment]
12 Pro.

**Comment by vincode-io** [comment]
I was able to recreate this. It only happens when you launch directly to the collections scene and go into a collection. After that things start lining up again when you return to the collections scene.

This bug actually looks different on iOS 15. The collections scene is aligned correctly when launched, but the "timeline" isn't and it jiggles one to put itself into alignment.

Since the buttons are configured in `viewDidLoad` and the bug changes in iOS 15, I'm going to assume this is an Apple bug, unless you think differently.

**Comment by stuartbreckenridge** [comment]
Seems fair. Numbers does it as well. 😆

https://user-images.githubusercontent.com/7046652/130438189-fac01211-c47b-4a0a-b0e9-27f8ceeedb92.MOV
