### ISSUE TITLE
Link Support

### ISSUE THREAD

**Issue by vincode-io** [vincode-io/Zavala#11]
* Links
  * Link dialog should have both the text being linked and the link itself
  * Should be able to link to any Outline
  * Should be able to search for Outlines in the link dialog
  * Implement a custom scheme so that external apps can also link to Outlines

**Comment by flansquatch** [comment]
When adding links to text (Command-K), the pre-selected field in the new window is “Text” instead of “Link”, which slows down the actual linking process by having to use the pointer or the Tab key to be able to paste the link and conclude the operation. 

Would it be possible to have “Link” be the preselected field?

**Comment by vincode-io** [comment]
Good suggestion. I'll add it to the 1.1 release.
