### ISSUE TITLE
Make theme match the native Apple Notes App

### ISSUE THREAD

**Issue by rcastro0** [vincode-io/Zavala#171]
Thank you for the great app. I tweaked the theme a bit to fit my liking -- I could only change fonts, though, not line spacing.

After I was done, I put one of Zavala's notes windows side by side with Apple Notes. I noticed that I had naturally adjusted font sizes to be just about that size (that meant decreasing the title font to 20px, for instance).

The dafault font seems to be the same as Apple Notes (which is great).

However _the color is not_, and I think it would look better if it was. In particular, Zavala uses black, and Notes uses a dark grey which makes all the text look finer (and IMHO nicer).

Also, I noticed that the file location fonts on the first column to the left could perhaps be more like Apple Notes (I am talking of details such as Bold/Normal, font size)...

Just some ideas... I will use the program as it is, it is already plenty nice.

**Comment by Tristram1** [comment]
I second the thank you!

Notes and Zavala UI at first glance are much the same - but the colors are different... And I like that because that help me easily distinguish they are different apps.  While themes might be a good idea, am fine with the default choices

I too would like to be able to adjust the line spacing... but I definitely prefer Zavala's line spacing to that of Notebook.

**Comment by vincode-io** [comment]
I don't have any plans to make Zavala look more like Apple Notes. A really good, professional designer came up with the current fonts, layout, etc... I'm quite happy with it.

I hear you guys about line spacing. It is being tracked as #153.
