### ISSUE TITLE
Feature Request: Templates

### ISSUE THREAD

**Issue by pramjan90** [vincode-io/Zavala#172]
Hi Maurice,

First off, thanks a ton for sharing this incredible outliner with the rest of us! Also, your camper-van life is an inspiration :)

I think templates are a common feature in many similar apps (like Logseq, Obsidian, etc.) to quickly create notes with a certain structure. 

Would it be possible to have a forward-slash command prompt - which would ask which command to execute, and then we could choose a certain template by typing "template <name>"?

**Comment by vincode-io** [comment]
@pramjan90 the template feature can behave very differently between different applications. Do you have a specific application in mind that you feel has done it well?

I did add the Duplicate function so that you could use and outline or a row in an outline as a template of sorts. I'm sure it isn't what you are asking for, but I thought I would point it out in case it helps you any.

**Comment by pramjan90** [comment]
@vincode-io  Thanks, actually, since posting this comment, I started duplicating specific outlines, with the tag "template", which are then easy to find. So there really isn't any need for the template feature (I think its not important to have).

**Comment by vincode-io** [comment]
Awesome. I'm glad it is working for you.
