### ISSUE TITLE
Support convert any line to checkbox mode

### ISSUE THREAD

**Issue by rexzhang** [vincode-io/Zavala#253]
This way we can use it as a to-do list

**Comment by vincode-io** [comment]
You can already use Zavala as a to-do list. I use it that way all the time.

You can Complete and Uncompleted a row using the keyboard shortcut, the Row context menu, or by swiping to the right. It will then dim and strike-out the row so that you know your task has been completed.

I don't plan on adding an actual checkbox to the row. We've already got many ways to Complete and Uncomplete items.

I hope this helps.

**Comment by rexzhang** [comment]
This is a good solution and supports easy operation on touch screens. Thanks you!
