### ISSUE TITLE
Copy as Markdown

### ISSUE THREAD

**Issue by vincode-io** [vincode-io/Zavala#6]
I think it will be handy to be able to be able to copy an outline or part of an outline as Markdown.  This would be useful for maintaining release notes in an outline that you could easily export and paste into Github.

I wonder if Markdown shouldn't just be the default string representation of the outline.  I'd like to be able to just drag to a text box and have the outline paste in Markdown.

**Comment by pramjan90** [comment]
Is there any chance of reviving this feature in the current version of the app? It certainly would be very handy to copy as markdown. as @brentsimmons points out, markdown to outline is diffucult, but I think most users would agree that is of secondary importance in this case.
Since we have export to markdown, can't we have copy to markdown?

Regards,
Pramod.

**Comment by vincode-io** [comment]
@pramjan90 All rows _are_ copied as Markdown by default. Could you explain why you think they are not?

The difficult part is pasting into Zavala with Markdown. [This has been requested](https://github.com/vincode-io/Zavala/issues/147) and I may take a look at it in a future release.
