### ISSUE TITLE
down arrow key does not move cursor in line of text

### ISSUE THREAD

**Issue by Thomas-U** [vincode-io/Zavala#81]
When the cursor is positioned somewhere in a line of text – after correcting a typo for example – the down arrow should move it to the end of the current text.

Right now it does nothing.

Z 1.0 (21) - 11.2.3  · MacMini M1

**Comment by vincode-io** [comment]
With outliners the up and down arrow keys move you from row to row. I'm assuming you are on the last row and hitting the down arrow key, which is why nothing is happening.

I'm honestly not sure what the correct behavior is here. Should the down arrow be reserved for moving down to the next row? Should the down arrow take you to the end of the line and only if you are at the end of the line, go down to the next row?

@brentsimmons Is this something you can help us understand better?

**Comment by brentsimmons** [comment]
When you are in structure mode (not editing a line, just selecting rows), down arrow should move row-by-row.

When in text editing mode, down arrow should move as if the entire outline is a text document. It goes down visible line by line, preserving position, moving from outline row to outline row as needed.

When you’re in text editing mode on the very last visible line of the very last row, down arrow should move the cursor to the end of the line.

(OmniOutliner is a good reference for this.)

**Comment by vincode-io** [comment]
Thanks Brent!

My copy of OmniOutliner had started complaining that I didn't have a license and then crashing shortly after that on launch. I had a subscription to it, so I cancelled it. Your note prompted me to check again and it looks like they got that bug resolved. I should be able to test against OmniOutliner again.

I fixed both the go to the end of line issue reported by @Thomas-U and the behavior problem of not maintaining the cursors horizontal position, pointed out by @brentsimmons.
